app = "myapp-frontend-staging"
primary_region = "iad"

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  path = "/env.js"
  port = 80
  timeout = "5s"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
