#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED_ENV_FILE="$PROJECT_ROOT/.env.supabase.local"

if ! command -v supabase >/dev/null 2>&1; then
    echo "Supabase CLI is required for local auth. Install it, then retry." >&2
    exit 1
fi

read_status_value() {
    local name="$1"

    printf '%s\n' "$SUPABASE_STATUS" \
        | sed -n "s/^${name}=\"\\(.*\\)\"$/\\1/p" \
        | head -n 1
}

write_generated_env() {
    SUPABASE_STATUS="$(supabase status -o env)"

    local api_url
    local publishable_key
    local secret_key
    local jwt_secret

    api_url="$(read_status_value API_URL)"
    publishable_key="$(read_status_value PUBLISHABLE_KEY)"
    secret_key="$(read_status_value SECRET_KEY)"
    jwt_secret="$(read_status_value JWT_SECRET)"

    if [ -z "$api_url" ] || [ -z "$publishable_key" ] || [ -z "$secret_key" ]; then
        echo "Unable to read local Supabase credentials from \`supabase status\`." >&2
        exit 1
    fi

    cat > "$GENERATED_ENV_FILE" <<EOF
# Generated by scripts/supabase-local.sh. Do not commit.
SUPABASE_URL=${api_url}
SUPABASE_AUTH_URL=${api_url}
SUPABASE_PUBLISHABLE_KEY=${publishable_key}
SUPABASE_SECRET_KEY=${secret_key}
SUPABASE_JWT_SECRET=${jwt_secret}
SUPABASE_JWT_ISSUER=${api_url}/auth/v1
EOF
}

case "${1:-start}" in
    start)
        supabase start
        write_generated_env
        ;;
    stop)
        supabase stop
        ;;
    status)
        supabase status
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 2
        ;;
esac
